using ABCRetail.Functions.Models;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;
using System.Net;
using System.Text.Json;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore; // <-- Add this
using System.IO;                   // <-- Add this

namespace ABCRetail.Functions
{
    public class OrdersApi
    {
        private readonly ILogger<OrdersApi> _logger;
        private readonly AppDbContext _context; // <-- Change this

        // Inject AppDbContext
        public OrdersApi(ILogger<OrdersApi> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context; // <-- Assign this
        }

        [Function("GetOrders")]
        public async Task<HttpResponseData> GetOrders(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "orders")] HttpRequestData req)
        {
            _logger.LogInformation("Request to get all orders (SQL).");

            try
            {
                // --- NEW EF Core Logic ---
                // This query uses the navigation properties to automatically join
                // Customer and Product tables.
                var orderViewModels = await _context.Orders
                    .Include(o => o.Customer) // <-- Join Customer
                    .Include(o => o.Product)  // <-- Join Product
                    .Select(o => new OrderViewModel // Project to a view model
                    {
                        OrderId = o.OrderId.ToString(), // Convert int to string for view model if needed
                        CustomerName = o.Customer.Name,
                        ProductName = o.Product.Name,
                        TotalAmount = o.TotalAmount,
                        OrderDate = o.OrderDate
                    })
                    .ToListAsync();
                // --- End EF Core Logic ---

                var response = req.CreateResponse(HttpStatusCode.OK);
                await response.WriteAsJsonAsync(orderViewModels);
                return response;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while fetching orders (SQL).");
                var errorResponse = req.CreateResponse(HttpStatusCode.InternalServerError);
                await errorResponse.WriteStringAsync("An error occurred on the server.");
                return errorResponse;
            }
        }

        [Function("CreateOrder")]
        public async Task<HttpResponseData> CreateOrder(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "orders")] HttpRequestData req)
        {
            _logger.LogInformation("Request to create an order (SQL).");
            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();

            if (string.IsNullOrEmpty(requestBody))
            {
                return req.CreateResponse(HttpStatusCode.BadRequest);
            }

            var orderData = JsonSerializer.Deserialize<Order>(requestBody, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            // Create new Order object. The OrderId will be generated by the DB.
            var order = new Order
            {
                CustomerId = orderData.CustomerId, // This is now an int
                ProductId = orderData.ProductId,   // This is now an int
                TotalAmount = orderData.TotalAmount,
                OrderDate = DateTime.UtcNow // Set the order date upon creation
            };

            // --- NEW EF Core Logic ---
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            // --- End EF Core Logic ---

            var response = req.CreateResponse(HttpStatusCode.Created);
            await response.WriteAsJsonAsync(order); // Returns the new order, now with its DB-generated OrderId
            return response;
        }
    }
}
// You no longer need the custom AsyncEnumerableExtensions